### ISSUE TITLE
Ajout des métadonnées d'heure d'acquisition (temps GPS min/max)

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/ALSroads#39]
L'idée est de déterminer, pour chaque segment de route, la date exacte pour laquelle l'analyse des données LiDAR est valide. Avoir cette info permettrait ensuite de comparer le segment avec d'autres sources de données (photos aériennes / satellitaires) pour lesquelles la date d'acquisition est aussi connue. L'info du temps GPS minimal et maximal trouvé dans les points de la route pourrait être ajoutée à la table attributaire avec le reste des métadonnées. Seulement les fichiers LAZ pour lesquels le GPS Time Global Encoding Byte est à 1 devraient être considérés puisqu'avoir un temps en Seconds-of-week est pas mal inutile.

Dis-moi si ce serait un ajout trop spécifique. C'est une analyse que je peux toujours faire par après avec un autre script. Je ne me disais que comme l'extraction des points était déjà faite, ça éviterait d'en refaire une deuxième seulement pour aller chercher cette info-là, mais ce serait pas exagéré non plus de la refaire.

**Comment by Jean-Romain** [comment]
Je pense que c'est hyper specifique et pas très robuste. Entre les fichier sans gptime, le fait que gpstime n'est pas loadé par default, les gpstime inccorecte, les different standards, le fait que le je suis pas convaincu que le Glocal Encoding byte est toujours respecté. Bref je trouve ca casse gueule.

**Comment by jfbourdon** [comment]
C'est bien correct, je me ferai donc un script à côté pour ça.

Pour avoir souvent eu à retracer le moment exact de passages LiDAR, je te confirme également que le Global Encoding byte n'est pas toujours respecté et que ça peut rapidement être tout un casse-tête.
