### ISSUE TITLE
`find_path()` cause parfois la création d'un MULTILINESTRING

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/ALSroads#42]
Très rarement, il arrive que l'[opération de retrait des portions de segments dans les caps](https://github.com/Jean-Romain/ALSroads/blob/673f50f2638c9567a77da6b2e089216b8ccd69e3/R/lcp_tools.R#L208) engendre la création d'un MULTILINESTRING. Dans le cas présent, le segment (ligne verte) sort du cap (hachuré rouge), mais le recroise une deuxième fois ([fichiers d'exemple](https://transfert.mffp.gouv.qc.ca/?ShareToken=32A90055EDDC4BCA93F6B7BFE280CC40DDB643E7)).

![image](https://user-images.githubusercontent.com/32580398/157368742-ddd0c742-3bbf-406d-8ed8-d57584d35cfe.png)

Lorsque ça arrive, le code plante à la ligne suivante puisque `sf::st_line_sample()` ne peut fonctionner que sur un LINESTRING.
https://github.com/Jean-Romain/ALSroads/blob/673f50f2638c9567a77da6b2e089216b8ccd69e3/R/road_tools.R#L21

**Comment by Jean-Romain** [comment]
```r
library(ALSroads)
library(lidR)
library(raster)

setwd("issue 42/")
ctg <- readLAScatalog("point_cloud.laz")
dtm <- raster("dtm.tif")
road <- sf::st_read("line.gpkg")

plot(dtm, col = gray(1:50/50))
plot(ctg, add = TRUE)
plot(road$geom, add = T)

corrected_road <- measure_road(road, ctg = ctg, dtm = dtm)
#> Erreur dans sf::st_line_sample(road, sample = at) : 
#> inherits(x, "sfc_LINESTRING") n'est pas TRUE
```

**Comment by Jean-Romain** [comment]
Fixed in c83cbd33
