### ISSUE TITLE
Plan to change from raster to terra + speed up

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/ALSroads#49]
@jfbourdon @ilythiamorley 

I've a plan to change the function `measure_road` in such a way that it will no longer uses the package `raster` but `terra` exclusively. I think it should be mostly invisible for you except that will need to load the DTM with `terra::rast()`. But I'm expecting some troubleshooting anyway.

In addition, one of the bottleneck of the function in term of speed it the computation of the transition matrix with the `gdistance`  package. I modified this function and gained a ten fold speed up at this step in my development branch. I will put that in the master branch and you should see a significant speed up.

I'm not going to make the change right now because I'm working on other stuff but this should come soon

**Comment by jfbourdon** [comment]
Nice but does `terra` itself has been fix to stop pushing error and warning messages all the time? Also, does your improvement with transition matrix computation can/will be ported to `gdistance` itself or is it only for `ALSroads` and breaks compatibilty with native functions from `gdistance`?

**Comment by Jean-Romain** [comment]
> terra itself has been fix to stop pushing error and warning messages all the time?

Sadly no

> Also, does your improvement with transition matrix computation can/will be ported to gdistance itself or is it only for ALSroads

Only for ALSroads. I optimized a specific bottleneck  by changing a generic code allowing to apply any user defined function into a specialized version that only applies `mean`.

> And breaks compatibilty with native functions from gdistance

I'm not sure what did you mean. `ALSroad::transition` no longer call `gdistance::transition` but a specialized function. However the output is still a `transitionMatrix` from `gdistance`.

**Comment by jfbourdon** [comment]
You understood my question correctly, I was looking to know if the transition matrix produced would still be a `transitionMatrix` object. Thanks.

**Comment by Jean-Romain** [comment]
I pushed a modified version of `transition` that is faster and support both `raster` and `terra`. So I did not change the other parts of the code to work with `terra` yet
