### ISSUE TITLE
Error: Internal error. A MULTILINESTRING has been returned. Please report

### ISSUE THREAD

**Issue by ilythiamorley** [Jean-Romain/ALSroads#55]
Hi JR, 

I have been running the measure_roads function on a large road network. After running without issue on over 1000 roads,  I got this error:
```
> corrected_road <- ALSroads::measure_roads(road = road, ctg = ctg, dtm = dtm)
Road 1 of 1  Progress: ...................Error: Internal error. A MULTILINESTRING has been returned. Please report
> 
```
I have included a reproducible example with my data and code. 

Let me know if this is something I can fix easily. 

Cheers, 
Lithy 

Link to data and code:
https://drive.google.com/file/d/1_oK2oBbfIW3WHm4MpuMQFSkbIZOFgT6a/view?usp=sharing

**Comment by Jean-Romain** [comment]
Good, I added this error yesterday to cactch limit cases. I'll have a look

**Comment by Jean-Romain** [comment]
Fixed. I'm confident this fix won't create more trouble. Yet you may encounter other edge cases with weird road geometries.

**Comment by Jean-Romain** [comment]
@jfbourdon update, my previous bug fix is generating this new error.
