### ISSUE TITLE
Error in `[.data.frame`(x, i) : undefined columns selected

### ISSUE THREAD

**Issue by ilythiamorley** [Jean-Romain/ALSroads#56]
Hi JR, 

I am getting a new error on one of my roads, and I can not see an apparent cause. 

My code ran without errors for over 6,000 roads and then flagged this road up. 

Here is the error I get: 

```
> corrected_road <- ALSroads::measure_roads(road = road, ctg = ctg, dtm = dtm)
Road 1 of 1  Progress: .......................................Error in `[.data.frame`(x, i) : undefined columns selected
```
I have isolated the road, tile, and DTM here: 
https://drive.google.com/file/d/1u3dr5vAkphhCLL-v1JOVeg5zs-oNK8lo/view?usp=sharing

Thanks for all the help! 

Cheers, 
Lithy

**Comment by Jean-Romain** [comment]
Is is a random error? I cannot reproduce

**Comment by ilythiamorley** [comment]
It may be random, seems to happen on that specific road randomly.  It just ran correctly, so maybe the error is from something else entirely. 

I will let you know if it happens again, thank you!

**Comment by ilythiamorley** [comment]
Hi JR, 

I have been running measure_roads() over large areas (15,000 + road segments), and I am getting the same error as above. 

When I try to run the code on a single road to identify the issue, I do not get the error, so I cannot reproduce it. 

Is there a way to have the function save the roads that have been found? 

For example, in this case, I was successful until road 7869 of 15617. The error means I am back to 0 again. 

Thanks for all the help, 
Lithy

**Comment by Jean-Romain** [comment]
I added an error handling structure. It should not fail anymore. Instead it should return `NULL` if it fails with a warning like

```
warning :
Error in road 10: NULL returned.
The error was: Error in `[.data.frame`(x, i) : undefined columns selected 
```

It does not fix the problem but at least bypasses it. Better than nothing.

**Comment by ilythiamorley** [comment]
Thank you, that will help a lot.
