### ISSUE TITLE
Déviation à des ponceaux par absence de points sol

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/ALSroads#57]
Le problème vient de la classification des données en entrée, mais je me demande si l'algo pourrait tout de même être plus robuste dans ces situations. En gros, la classification originale des points sol laisse non classé certaines sections de route au-dessus de ponceaux où le ruisseau est particulièrement enclavé (violet = points sol, jaune = non classé):
![2022-06-21_001029](https://user-images.githubusercontent.com/32580398/174878130-ea525c89-07bf-42ec-a29b-55f50eddaead.png)

Et voilà dans un cas (47.15938439, -71.72185581) l'impact sur le résultat (orange = tracé corrigé, blanc = tracé original):
![2022-06-21_001030](https://user-images.githubusercontent.com/32580398/174878824-ea58fcad-9a64-4892-b797-eb57de67da1a.png)

J'ai mis cet exemple ainsi que trois autres ici: https://transfert.mffp.gouv.qc.ca/?ShareToken=156F8EF77AAD52FCE6A8F9B594D5C6C038ED7451

Dans tous les cas, il n'y a pas de polygones de surfaces d'eau pouvant être utilisé, car ce sont de trop petits ruisseaux. Toutefois, en principe, on devrait toujours avoir au minimum une ligne désignant le ruisseau dans nos couches d'hydrographie.

Comme solution, j'envisage toutefois de tout simplement reclassifier le nuage de points avec _lasground_ de LAStools, même si ça allonge le temps de traitement. Je dois de toute façon faire un paquet de pré-traitements sur nos tuiles pour gérer les chevauchement de fuseaux MTM, les points dupliqués, créer les LAX, en plus de devoir regénérer les MNT. Donc si tu penses à une solution robuste tant mieux, mais sinon j'ai un plan B qui fonctionne.

Piste d'amélioration générale: Est-ce envisageable de faire en sorte que l'algorithme favorise le trajet minimisant le dénivelé cumulatif? En principe, une route devrait pas mal toujours être plus _smooth_ que l'environnement puisque durant sa construction on aura tendance à remplir les creux et à couper les crêtes.

**Comment by Jean-Romain** [comment]
Je viens de regarder dans tes example 3594 et 8762 et en absence de point sol on a des 0 puisque le sol calculé se trouve plus bas dans le lit du ruisseaux avec des pentes énormes qui indiquent qu'on ne peut pas passer.

Ca se résous facilement sur des petites distances en interdisant les 0. C'est ce que je fais dans mon travail actuel le raster de conductivity ne peut plus avoir de valeurs en dessous de 0.1 et ca permet de passer partout sans avoir de coût infini. Si je fais ca ca passe. Après je ne sais pas quelle consequences ca va avoir à plus large échelle et peut être que certain chemin qui étaient contraint par les 0 (coût infini) vont pouvoir passer par des endroits infranchissable. J'ai ajouté un paramètre. Si tu mets 0 ca restore le comportement d'avant

```r
param = alsroads_default_parameters
param$conductivity$sigma_min = 0
corrected_road <- ALSroads::measure_roads(road = road, ctg = ctg, dtm = dtm, param = param)
```
