### ISSUE TITLE
Install issue: Warning message: Package had non-zero exit status

### ISSUE THREAD

**Issue by ilythiamorley** [Jean-Romain/ALSroads#59]
Hi JR, 

I am getting this error when I install the ALSroads package: 

```
remotes::install_github("Jean-Romain/ALSroads")
...
ERROR: unable to collate and parse R files for package 'ALSroads'
* removing 'C:/Users/ilythia6/AppData/Local/R/win-library/4.2/ALSroads'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/ilythia6/AppData/Local/Temp/RtmpsfUpnO/filed58107c4a1b/ALSroads_0.2.0.tar.gz’ had non-zero exit status
```
The package was working fine before, but I had to do some updates.

I have restarted, updated R, removed the package from file, and reinstalled it. 

Do you have any ideas about what is causing this? 

Thanks for all the help,

L

**Comment by Jean-Romain** [comment]
I missed a coma in my latest fix and did not check the code. This also means you did not used the fix I made for you in #56 :-)
