### ISSUE TITLE
Corrected road nodes order reversed from original road

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/ALSroads#62]
For some roads, the resulting road is flipped relative to the orientation of the input road. This cause an issue when checking for anomalies with `check_road_differences()` as their respective startpoint and endpoint of both lines are falsely very far appart.

Data: https://transfert.mffp.gouv.qc.ca/?ShareToken=7CC2BD611B50E2D04CB6E05E9474D0397DA39551
Tested with ALSroads [d39fc2c](https://github.com/Jean-Romain/ALSroads/commit/d39fc2c83039ad1d15102a1ef1737cdb45b8241e)

```R
library(ALSroads)
library(lidR)
library(raster)

ctg <- readLAScatalog("point_cloud.laz")
dtm <- raster("dtm.tif")
road <- sf::st_read("line.gpkg")

corrected_road <- measure_road(road, ctg = ctg, dtm = dtm)

plot(road$geom, col="red")
coord <- sf::st_coordinates(road$geom)[c(8,12),1:2]
arrows(coord[1,1], coord[1,2], coord[2,1], coord[2,2], col="red", lwd=4)
plot(corrected_road$geom, add=T, col="blue")
coord <- sf::st_coordinates(corrected_road$geom)[8:9,1:2]
arrows(coord[1,1], coord[1,2], coord[2,1], coord[2,2], col="blue", lwd=4)

# Checking differences with original road
check_road_differences(corrected_road, road, "primaryindex")  # really different from orignal line
#   primaryindex area_over_perimeter      P50     P90     P100  end_max
# 1        58762            3.635277 238.2542 420.677 451.2766 451.2766

check_road_differences(sf::st_reverse(corrected_road), road, "primaryindex")  # rather close from orignal line
#   primaryindex area_over_perimeter      P50      P90     P100  end_max
# 1        58762            3.635277 6.946467 22.21269 25.11234 5.723174
```

![image](https://github.com/Jean-Romain/ALSroads/assets/32580398/d42cd0bb-ec17-4d13-94bb-23f5ac856187)

**Comment by Jean-Romain** [comment]
Corrigé, l'autre bug c'était le même problème

**Comment by jfbourdon** [comment]
Merci. Peux-tu pousser le commit aussi sur la branche principale? Je ne sais si c'était voulu, mais présentement, c'est seulement sur _drive_road_.

**Comment by Jean-Romain** [comment]
Je crois que dans `drive_road` J'ai pas mal changé la fonction de conductivité pour avoir un meilleur output pour vecnet (qui ne calcul pas la conductivité). Sauf que je ne peux pas merger au risque de casser l'évaluation de l'état de la route puisque la conductivité version 1 est utilisée
