### ISSUE TITLE
Splitted roads aren't always merged correctly and show straight line

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/ALSroads#63]
When a road is splitted in chunks because it is too long to be processed in only one, the corrected road sometime show a straight line between both ends of the line. The computed metrics doesn't seem to be affected by this line that can cross any terrain. I'm under the impression that fixing #62 will also fix this issue.

Data: https://transfert.mffp.gouv.qc.ca/?ShareToken=6E322A3282A5DB898B3BE3431290D6E0F313A2F7
Tested with ALSroads [d39fc2c](https://github.com/Jean-Romain/ALSroads/commit/d39fc2c83039ad1d15102a1ef1737cdb45b8241e)

```r
library(ALSroads)
library(lidR)
library(raster)

ctg <- readLAScatalog("point_cloud.laz")
dtm <- raster("dtm.tif")
road <- sf::st_read("line.gpkg")

corrected_road <- measure_road(road, ctg = ctg, dtm = dtm)

plot(road$geom, col="red", lwd=4)
plot(corrected_road$geom, add=T, col="blue", lwd=2)
```

![image](https://github.com/Jean-Romain/ALSroads/assets/32580398/594ae444-d7c7-4a3e-a3a5-896ac0568b64)

**Comment by Jean-Romain** [comment]
Je crois que ce problème est le même que l'autre. Les sous-parties sont inversées.
