### ISSUE TITLE
ERROR install rgeos rgdal dependancies

### ISSUE THREAD

**Issue by pobsteta** [Jean-Romain/ALSroads#65]
Bonjour Jean-Romain,

J'essaie d'installer ALSRoad sur R mais j'ai cette erreur :

── R CMD build ──────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\P-OBSTETAR\AppData\Local\Temp\Rtmpk7LKXd\remotes697856247b98\Jean-Romain-ALSroads-1ccce3b/DESCRIPTION' (585ms)
─  preparing 'ALSroads':
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'ALSroads_0.2.0.tar.gz'
   
ERROR: dependencies 'rgdal', 'rgeos' are not available for package 'ALSroads'

Je pense que ça vient du fait que rgdal et rgeos ont été abandonné depuis cette année, penses-tu faire une maj du paquet ?
@+

**Comment by Jean-Romain** [comment]
J'ai retiré la dépendance à `rgdal` qui n'était là que pour `raster` mais `raster` a été mis à jour depuis. J'ai mis `rgeos` en `Suggest` ça devrait s'installer sans problème. Par contre @jfbourdon il faut réécrire les fonctions de `snap_tools.R` avec `sf`.

J'ai aussi corrigé des trucs avec R CMD check et corrigé la documentation de certaines fonctions.
