### ISSUE TITLE
Erreur lors du calcul measure_road ?

### ISSUE THREAD

**Issue by pobsteta** [Jean-Romain/ALSroads#66]
Bonjour,

j'obtiens une erreur lors de l'utilisation de la fonction measure_raod que je ne comprends pas ?
data : 
[trace1.zip](https://github.com/Jean-Romain/ALSroads/files/13545863/trace1.zip)
las : https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/SE/LHD_FXX_1042_6878_PTS_C_LAMB93_IGN69.copc.laz
mnt : 
[mnt.zip](https://github.com/Jean-Romain/ALSroads/files/13545961/mnt.zip)

![image](https://github.com/Jean-Romain/ALSroads/assets/932599/d4e0229b-b733-4dfc-914d-c5805ff80a3e)

**Comment by pobsteta** [comment]
Les fichiers joints aux messages ne sont pas suffisants ?

**Comment by Jean-Romain** [comment]
Il y a les données mais pas le code.

**Comment by pobsteta** [comment]
Le code est sur la copie écran juste passer la commande result <- measure_roads(ctg, piste, mnt_tin) avec ctg = las, piste = data er mnt_tin = mnt

**Comment by pobsteta** [comment]
Effectivement avec raster::raster(mnt) plutôt que terra::rast(mnt) ça passe !
